variant-calls:
  # Listing of callsets and corresponding paths, representing variant call results
  # from different pipelines or different configurations of the same pipeline.
  # Multiple entries are possible.
  DD-dragen-agilent:
    labels:
      site: DD
      pipeline: dragen
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/DD_NA12878.gatk.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  BO-agilent:
    labels:
      site: BO
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/BO_cropbioBonn_WGGC_WES_CN_200M.vcf.gz
    benchmark: giab-NA12878-agilent
  CO-agilent:
    labels:
      site: CO
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/CO_SID118711_AID130848.cmb.func.vcf.gz
    benchmark: giab-NA12878-agilent
  DD-gatk-agilent:
    labels:
      site: DD
      pipeline: gatk
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/DD_NA12878.gatk.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  GHGA-haplotypecaller-agilent:
    labels:
      site: GHGA
      pipeline: gatk
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/GHGA_haplotypecaller_A006850052.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  KI-agilent:
    labels:
      site: KI
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/KI_Indiv_A006850052_118711_Sample_A006850052_118711.dedup.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-freebayes-agilent:
    labels:
      site: TB
      pipeline: freebayes
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/TB_FreeBayes_NA12878.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-haplotypecaller-agilent:
    labels:
      site: TB
      pipeline: gatk
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/TB_HaplotypeCaller_NA12878.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-ngscn-agilent:
    labels:
      site: TB
      pipeline: ngscn
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/TB_NGSCN-benchmark-NCCT_var.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  TB-strelka-agilent:
    labels:
      site: TB
      pipeline: strelka
    subcategory: agilent
    path: resources/ftp/wes_agilentv6/TB_Strelka_NA12878_variants.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt
  DUE-varlociraptor:
    zenodo: 6396505
    path: resources/zenodo/DUE-varlociraptor/NA12878.present.fdr-controlled.bcf
    benchmark: giab-NA12878-agilent
    subcategory: agilent
    labels:
      site: DUE
      pipeline: dna-seq-varlociraptor


# Optional: paths to custom read data, instead of downloading public exome dataset.
custom-benchmarks:
  giab-NA12878-agilent:
    genome: NA12878
    fastqs:
      - resources/ftp/wes_agilentv6/118711_1.fq.gz
      - resources/ftp/wes_agilentv6/118711_1.fq.gz
    target-regions: resources/ftp/wes_agilentv6/Agilent_v6.bed
    # whether given target regions are on hg19
    grch37: false

# Optional: limit testing and downloading to given regions
limit-regions:
  activate: false
  bed: path/to/regions.bed

# Set to true to run analysis on GRCh37 instead of GRCh38
grch37: false
