variant-calls:
  # Listing of callsets and corresponding paths, representing variant call results
  # from different pipelines or different configurations of the same pipeline.
  # Multiple entries are possible.
  DD_NA12878.dragen-agilent: 
    path: resources/ftp/wes_agilentv6/DD_NA12878.gatk.vcf.gz
    benchmark: giab-NA12878-agilent
    rename-contigs: resources/rename-contigs/ucsc-to-ensembl.txt

# Optional: paths to custom read data, instead of downloading public exome dataset.
custom-benchmarks:
  giab-NA12878-agilent:
    genome: NA12878
    fastqs:
      - resources/ftp/wes_agilentv6/118711_1.fq.gz
      - resources/ftp/wes_agilentv6/118711_1.fq.gz
    target-regions: resources/ftp/wes_agilentv6/Agilent_v6.bed
    # whether given target regions are on hg19
    grch37: false

# Optional: limit testing and downloading to given regions
limit-regions:
  activate: false
  bed: path/to/regions.bed

# Set to true to run analysis on GRCh37 instead of GRCh38
grch37: false